In [ ]:
#### NAMES: NIYITEGEKA JANVIER
#### COUNTRY :RWANDA
#### COURSE: Deep Learning with PyTorch
#### Pytorch Tensor Basics

In [ ]:
This Jupyeter notebook gives a short introduction about PyTorch and about the chosen functions

The PyTorch is an open source neural networks library developed by facebook for implementing Deep learning framework

            .Function1
            .Function2
            .Function3
            .Function4
            .Function5
            .Function6
            .Function7
            .Function8
            .Function9
            .Function10
            .Function11
            .Function12

#### 1)Function 1: new_tensor(data, dtype=None, device=None, requires_grad=False)¶

This function create a tensor with similar type but different size as another predefined tensor and returns a new Tensor with data as the tensor data.By default, the returned Tensor has the same torch.dtype and torch.device as the given tensor.

In [82]:
#Parameters
# 1)data(array_like): returned Tensor copies data
# 2)dtype (torch.dtype, optional) – the desired type of returned tensor.
# 3)device (torch.device, optional) – the desired device of returned tensor.
# 4)requires_grad (bool, optional) – If autograd should record operations on the returned tensor. 

Examples:

In [38]:
# import PyTorch library
import torch

In [143]:
x=torch.tensor([1,8])

In [144]:
x

tensor([1, 8])

In [145]:
data = [[3, 1], [2, 3]]

In [146]:
#the following function create a new tensor with Tensor data copies and similar type to x tensor
new=x.new_tensor(data)

In [147]:
new

tensor([[3, 1],
        [2, 3]])

#### 2) Function 2:  new_full(size, fill_value, dtype=None, device=None, requires_grad=False)

This function create a tensor with similar type but different size as another predefined tensor and Returns a Tensor of size :'size' filled with: 'fill_value'. By default, the returned Tensor has the same torch.dtype and torch.device as the given tensor.

In [52]:
#Parameters
#  1) fill_value (scalar) – the number to fill the output tensor with.
# 2)dtype (torch.dtype, optional) – the desired type of returned tensor. Default:
# 3)device (torch.device, optional) – the desired device of returned tensor.
# 4)requires_grad (bool, optional) – If autograd should record operations on the returned tensor.

Examples:

In [65]:
#creating a tensor of 5 ones array
tensor1 = torch.ones((5,),dtype=torch.int32)
tensor1

tensor([1, 1, 1, 1, 1], dtype=torch.int32)

In [68]:
#creating new tensor similar type to tensor:tensor1 but with a matrix of 3 rows and 3 columns filled with :14
new2 = tensor1.new_full((3,3),14)

In [67]:
new2

tensor([[14, 14, 14],
        [14, 14, 14],
        [14, 14, 14]], dtype=torch.int32)

#### 3) Function3: torch.Tensor.item()

This function returns the value of the tensor as a standard Python number when tensor has only one element.

Example:

In [149]:
x=torch.tensor([10,14])

In [150]:
x

tensor([10, 14])

In [151]:
x.item()

ValueError: only one element tensors can be converted to Python scalars

In [72]:
y=torch.tensor((9))

In [73]:
y

tensor(9)

In [74]:
y.item()

9

#### 4) Function 4:  new_ones(size, dtype=None, device=None, requires_grad=False)

This function create a new tensor with similar type but different size as another predefined tensor and returns a tensor of size size filled with 1. By default, the returned tensor has the same torch.dtype and torch.device as the given tensor.

In [75]:
# Parameters
# 1) size (int...) – a list, tuple, or torch.Size of integers defining the shape of the output tensor.
# 2) dtype (torch.dtype, optional) – the desired type of returned tensor.
# 3) device (torch.device, optional) – the desired device of returned tensor.
# 4) requires_grad (bool, optional) – If autograd should record operations on the returned tensor. 

Examples:

In [77]:
x=torch.tensor((8),dtype=torch.int32)
x

tensor(8, dtype=torch.int32)

In [78]:
new3 = x.new_ones((4,5))
new3

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

#### 5) Function 5: torch.max(input)

This function returns the maximum value of all elements in the input tensor.

In [111]:
# Parameters
# input (Tensor) – the input tensor.

Example:

In [115]:
y = torch.randn(1,15)
y

tensor([[-0.6205,  0.4698,  0.0243, -1.1649, -1.4706,  0.7201,  1.3050, -3.0143,
         -0.6148, -0.8240,  1.0768,  1.2274,  1.1556, -0.1042, -1.4032]])

In [116]:
torch.max(y)

tensor(1.3050)

#### 6) Function 6: fill_diagonal_(fill_value, wrap=False)

Fill the main diagonal of a given tensor that has at least 2-dimensions. When dims>2, all dimensions of input must be of equal length. This function modifies the input tensor in-place, and returns the modified input tensor.

In [83]:
# Parameters
#  1) fill_value (Scalar) – the value to be filled in diagonal of the input tensor
#  2) wrap (bool) – the diagonal ‘wrapped’ after N columns for tall matrices.

Example:

In [88]:
a= torch.zeros((3,3))
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [89]:
a.fill_diagonal_(6)

tensor([[6., 0., 0.],
        [0., 6., 0.],
        [0., 0., 6.]])

#### 7) Function 7: torch.mul(input, other, out=None)

This function multiplies each element of the input: 'input' with the scalar: 'other' and returns a new resulting tensor. If input is of type FloatTensor or DoubleTensor, other should be a real number, otherwise it should be an integer

In [91]:
a = torch.rand(4)
a

tensor([0.4286, 0.9508, 0.9774, 0.2968])

In [92]:
torch.mul(a,1000)

tensor([428.5814, 950.7867, 977.3956, 296.8348])

#### 8) Function 8: torch.median(input)

This function returns the median value of all elements in the input tensor.

In [93]:
# Parameters
# input (Tensor) – the input tensor.

Example:

In [98]:
a = torch.randn(1,4)
a

tensor([[-0.1750, -0.3170, -1.3566, -0.0590]])

In [99]:
torch.median(a)

tensor(-0.3170)

#### 9) Function 9: torch.min(input) 

This function returns the minimum value of all elements in the input tensor.

In [100]:
# Parameter
# input (Tensor) – the input tensor.

In [105]:
a = torch.rand(1,10)
a

tensor([[0.4061, 0.0890, 0.3676, 0.2608, 0.2435, 0.0136, 0.0581, 0.0520, 0.4364,
         0.4369]])

In [106]:
torch.min(a)

tensor(0.0136)

#### 10) Function 10: torch.mean(input) 

This function returns the mean value of all elements in the input tensor.

In [107]:
#Parameter
# input (Tensor) – the input tensor.

Example:

In [109]:
a = torch.rand(1,20)
a

tensor([[0.8857, 0.8450, 0.9356, 0.0971, 0.4826, 0.2282, 0.4216, 0.9960, 0.3277,
         0.2514, 0.7061, 0.5306, 0.7077, 0.1940, 0.5885, 0.2834, 0.5331, 0.3804,
         0.2776, 0.4249]])

In [110]:
torch.mean(a)

tensor(0.5049)

#### 11) torch.matmul(input, other, out=None)

This function returns Matrix product of two tensors.

The behavior depends on the dimensionality of the tensors as follows:

If both tensors are 1-dimensional, the dot product (scalar) is returned.

If both arguments are 2-dimensional, the matrix-matrix product is returned.

If the first argument is 1-dimensional and the second argument is 2-dimensional, a 1 is prepended to its dimension for the purpose of the matrix multiply. After the matrix multiply, the prepended dimension is removed.

If the first argument is 2-dimensional and the second argument is 1-dimensional, the matrix-vector product is returned.

If both arguments are at least 1-dimensional and at least one argument is N-dimensional (where N > 2), then a batched matrix multiply is returned. If the first argument is 1-dimensional, a 1 is prepended to its dimension for the purpose of the batched matrix multiply and removed after. If the second argument is 1-dimensional, a 1 is appended to its dimension for the purpose of the batched matrix multiple and removed after. The non-matrix (i.e. batch) dimensions are broadcasted (and thus must be broadcastable). For example, if input is a (j \times 1 \times n \times m)(j×1×n×m) tensor and other is a (k \times m \times p)(k×m×p) tensor, out will be an (j \times k \times n \times p)(j×k×n×p) tensor.

In [122]:
# Parameters
# input (Tensor) – the first tensor to be multiplied
# other (Tensor) – the second tensor to be multiplied
# out (Tensor, optional) – the output tensor.


Example1:

In [123]:
a = torch.rand(3)
b = torch.rand(3)

In [124]:
torch.matmul(a,b)

tensor(0.8127)

Example2:

In [128]:
a1=a.new_full((2,2),2)
a1

tensor([[2., 2.],
        [2., 2.]])

In [132]:
a2 = torch.tensor([[1,3],[2,2]],dtype=torch.float32)
a2

tensor([[1., 3.],
        [2., 2.]])

In [133]:
torch.matmul(a1,a2)

tensor([[ 6., 10.],
        [ 6., 10.]])

#### 12) Function 12: torch.exp(input, out=None) 

This function returns a new tensor with the exponential of the elements of the input tensor input.

In [134]:
# parameters
# input (Tensor) – the input tensor.
# out (Tensor, optional) – the output tensor.

Example:

In [141]:
a=torch.tensor([1,0,2,4],dtype=torch.float64)
a

tensor([1., 0., 2., 4.], dtype=torch.float64)

In [142]:
torch.exp(a)

tensor([ 2.7183,  1.0000,  7.3891, 54.5982], dtype=torch.float64)